# Generated by Django 4.2 on 2026-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task', null=True)),
                ('status', models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], default=False, help_text='Task completion status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Task creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Task last updated timestamp')),
                ('due_date', models.DateTimeField(blank=True, help_text='Task due date', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Task priority level', max_length=20)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='tasks_task_created_5da2cb_idx'),
        ),
    ]
